spring.application.name=gateway-service-api
server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/activity-hub-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/activity-hub-realm/protocol/openid-connect/certs

# User service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE-API
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[0].filters[0]=PrefixPath=/user-service

# 2. Activity Service
spring.cloud.gateway.routes[1].id=activity-service
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICE-API
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/activity/**
spring.cloud.gateway.routes[1].filters[0]=PrefixPath=/activity-service

# 3. Feed Service
spring.cloud.gateway.routes[2].id=feed-service
spring.cloud.gateway.routes[2].uri=lb://FEED-SERVICE-API
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/feed/**
spring.cloud.gateway.routes[2].filters[0]=PrefixPath=/feed-service

# 4. BFF Service
spring.cloud.gateway.routes[3].id=bff-service
spring.cloud.gateway.routes[3].uri=lb://BFF-SERVICE-API
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/bff/**
spring.cloud.gateway.routes[3].filters[0]=PrefixPath=/bff-service

# 5. Tenant Service
spring.cloud.gateway.routes[4].id=tenant-service
spring.cloud.gateway.routes[4].uri=lb://TENANT-SERVICE-API
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/tenants/**
spring.cloud.gateway.routes[4].filters[0]=PrefixPath=/tenant-service

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true












